apiVersion: v1
kind: Service
metadata:
  name: refit-sender-svc
  labels:
    run: refit-sender-svc
spec:
  selector:
    app: refit-sender
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP