apiVersion: apps/v1
kind: Deployment
metadata:
  name: refit-receiver-deployment
  labels:
    app: refit-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refit-receiver
  template:
    metadata:
      labels:
        app: refit-receiver
    spec:
      containers:
        - name: refit-receiver
          image: 705922/refit-receiver
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-map-volume
            mountPath: /refit/config
      volumes:
      - name: config-map-volume
        configMap: 
          name: refit-receiver-config