apiVersion: v1
kind: Service
metadata:
  name: refit-receiver-svc
  labels:
    run: refit-receiver-svc
spec:
  selector:
    app: refit-receiver
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP